name: "HTMLProofer"
author: "chabad360"
description: "Test your rendered HTML files to make sure they're accurate."

inputs:
  directory:
    description: "The directory to scan"
    required: true
  arguments:
      description: "Passes through options"
      required: false
      default: ""

runs:
  using: "docker"
  image: "docker://chabad360/htmlproofer"
  entrypoint: "/entrypoint.sh"

branding:
  icon: "check"
  color: "green"