name: "HTMLProofer"
author: "chabad360"
description: "Scan your static page site with HTMLProofer"

inputs:
  directory:
    description: "The directory to scan"
    required: true

runs:
  using: "docker"
  image: "docker://chabad360/htmlproofer"
  entrypoint: "/entrypoint.sh"

branding:
  icon: "check"
  color: "green"